services:
  muse-audio:
    container_name: muse-audio
    build:
      context: .
      dockerfile: Dockerfile
    image: muse-audio:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ASPNETCORE_ENVIRONMENT=Production
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
